/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialoguer;

import controle.Modele.ModeleConteneur;
import java.awt.Toolkit;
import java.io.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import org.jdom2.*;
import org.jdom2.output.*;

/**
 *
 * @author Packard Bell
 */
public class Export extends javax.swing.JFrame {

        private ModeleConteneur unModeleConteneur= new ModeleConteneur();
    /**
     * Creates new form Export
     */
    public Export() {
        initComponents();
        complementGUI();
        unModeleConteneur= new ModeleConteneur(false);
        jTable1.setModel(unModeleConteneur);
    }
private void complementGUI(){
        //Affiche le logo
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo/Tholdisimplepetit.png")));
        //Affiche le nom
     setTitle("MEEC");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLab_Titre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Export = new javax.swing.JButton();
        jTextnombateau = new javax.swing.JTextField();
        jBut_Quitter = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(unModeleConteneur);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 500, 220));

        jLab_Titre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLab_Titre.setForeground(new java.awt.Color(255, 255, 255));
        jLab_Titre.setText("MEEC");
        getContentPane().add(jLab_Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 40));

        jLabel1.setText("Nom du bateau ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 324, 120, 30));

        jButton_Export.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jButton_Export.setText("Export XML");
        jButton_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExportActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Export, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 220, 40));

        jTextnombateau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextnombateau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnombateauActionPerformed(evt);
            }
        });
        getContentPane().add(jTextnombateau, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 220, 30));

        jBut_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accueil/quitter1.png"))); // NOI18N
        jBut_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_QuitterActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, 50));

        jButtonRetour.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 90, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond/fond.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_QuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBut_QuitterActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        Charge unecharge = new Charge();
        unecharge.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jButton_ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExportActionPerformed
       
        if (!jTextnombateau.getText().equals("")){ 
            String unbateau = jTextnombateau.getText();
            try{
                Element bateau = new Element("Bateau");
                Document doc = new Document(bateau);
                bateau.setAttribute(new Attribute("nom",unbateau));            
            
                    for(int roww: jTable1.getSelectedRows()){
                        Element conteneur = new Element("conteneur");
                        String unnumcont= String.valueOf(jTable1.getValueAt(roww, 0));
                        String uneposition= String.valueOf(jTable1.getValueAt(roww, 2));
                        String unNumCli= String.valueOf(jTable1.getValueAt(roww,3 ));
                        String[] ary = uneposition.split("");
                        String unQuai = ary[0] + ary[1]; 
                        String uneAllee = ary[2] + ary[3];
                        String unEmplacement = ary[4] + ary[5];
                        String unEtage = ary[6];
                        //ajout de conteneur
                        conteneur.addContent(new Element("numero").setText(unnumcont));
                        conteneur.addContent(new Element("quai").setText(unQuai));
                        conteneur.addContent(new Element("allee").setText(uneAllee));
                        conteneur.addContent(new Element("emplacement").setText(unEmplacement));
                        conteneur.addContent(new Element("etage").setText(unEtage));
                        conteneur.addContent(new Element("client").setText(unNumCli));
                        doc.getRootElement().addContent(conteneur);
                
                
                    }
                XMLOutputter xml = new XMLOutputter();
                xml.setFormat(Format.getPrettyFormat());
                DateFormat format = new SimpleDateFormat("yyyy_MM_dd_HH_mm_ss");
                Calendar calendar = Calendar.getInstance();
                xml.output(doc, new FileWriter("ExportXML\\Rotterdam_"+ format.format(calendar.getTime()) +".xml"));
                JOptionPane.showMessageDialog(null, "Fichier enregistré.","CONFIRME", JOptionPane.YES_NO_CANCEL_OPTION);
                } catch(Exception e){
                    e.printStackTrace();
                }
        }else {
            JOptionPane.showMessageDialog(null, "Nom du bateau non remplie.","ERREUR", JOptionPane.ERROR_MESSAGE);
            jTextnombateau.requestFocus();
        }
        
        
    }//GEN-LAST:event_jButton_ExportActionPerformed

    private void jTextnombateauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnombateauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnombateauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Export.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Export.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Export.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Export.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Export().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Quitter;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButton_Export;
    private javax.swing.JLabel jLab_Titre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextnombateau;
    // End of variables declaration//GEN-END:variables
}
