/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialoguer;

import entite.LeConteneur;
import entite.Taille;
import entite.Typeconteneur;
import java.awt.Color;
import java.awt.Toolkit;
import static java.lang.System.exit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Packard Bell
 */
public class FenModification extends javax.swing.JFrame {

    /**
     * Creates new form FenModication
     */
    public FenModification() {
        initComponents();
        complementGUI();
    }
    
    public FenModification(String numcont) {
        LeConteneur uncont = new LeConteneur(numcont);
        initComponents();
        complementGUI();
        jtextnumcont.setText(uncont.getLesEnrg().get(0).getNumid());
        String type=uncont.getLesEnrg().get(0).getType();
        String t=type.substring(0,1);
        Typeconteneur untype=new Typeconteneur(t);
       
        String tail=type.substring(1,2);
        Taille unetaille= new Taille(t,tail);
        String lar =unetaille.getLesEnrg().get(0).getTaillarg();
        String longue =unetaille.getLesEnrg().get(0).getTaillarg();
        String haut =unetaille.getLesEnrg().get(0).getTailhaut();
         jTextModele.setText(untype.getLesEnrg().get(0).getTypelibel()+"-"+longue+"''"+lar+"''"+haut);
        jTextIDType.setText(type);
        jTextEmplacement.setText(uncont.getLesEnrg().get(0).getEmplacement());
        jTextNumCli.setText(uncont.getLesEnrg().get(0).getNumcli());
           jTextDate.setText(String.valueOf(uncont.getLesEnrg().get(0).getDate_arrivee()));
    }
 private void complementGUI(){
        //Affiche le logo
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo/Tholdisimplepetit.png")));
        //Affiche le nom
     setTitle("MEEC");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtextnumcont = new javax.swing.JTextField();
        jTextDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextModele = new javax.swing.JTextField();
        jTextNumCli = new javax.swing.JTextField();
        jTextEmplacement = new javax.swing.JTextField();
        jTextIDType = new javax.swing.JTextField();
        jButtonRetour = new javax.swing.JButton();
        jBut_Quitter = new javax.swing.JButton();
        jLab_Titre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtextnumcont.setEnabled(false);
        getContentPane().add(jtextnumcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 130, -1));
        getContentPane().add(jTextDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 130, -1));

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 170, -1));

        jTextModele.setEnabled(false);
        getContentPane().add(jTextModele, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 250, -1));
        getContentPane().add(jTextNumCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 130, -1));

        jTextEmplacement.setEnabled(false);
        jTextEmplacement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmplacementActionPerformed(evt);
            }
        });
        getContentPane().add(jTextEmplacement, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 130, -1));

        jTextIDType.setEnabled(false);
        jTextIDType.setInheritsPopupMenu(true);
        jTextIDType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextIDType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 130, -1));

        jButtonRetour.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 90, 50));

        jBut_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accueil/quitter1.png"))); // NOI18N
        jBut_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_QuitterActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, 50));

        jLab_Titre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLab_Titre.setForeground(new java.awt.Color(255, 255, 255));
        jLab_Titre.setText("MEEC");
        getContentPane().add(jLab_Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond/fond.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_QuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBut_QuitterActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        MenuPrincipale uneFenetre = new MenuPrincipale();
        uneFenetre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jTextEmplacementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmplacementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmplacementActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numcont = jtextnumcont.getText();
        String emplacement =jTextEmplacement.getText();
        String numCli=jTextNumCli.getText();
        String date_arrivee=jTextDate.getText();
        try {
            Date unedate = new SimpleDateFormat("yyyy-mm-dd").parse(jTextDate.getText());
        
            LeConteneur unconteneur =new LeConteneur();
            if(unconteneur.modifier( numCli, date_arrivee, numcont)){
                JOptionPane.showMessageDialog(null, "Le conteneur a bien été modifié");    
                MenuPrincipale unefen = new MenuPrincipale();
                unefen.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Modification non effectué");
            }
        } catch (ParseException ex) {
           JOptionPane.showMessageDialog(null,"Erreur, date mal renseigné : AAAA-MM-JJ");
           jTextDate.requestFocus();
        }
        
                 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextIDTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenModification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Quitter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JLabel jLab_Titre;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextField jTextEmplacement;
    private javax.swing.JTextField jTextIDType;
    private javax.swing.JTextField jTextModele;
    private javax.swing.JTextField jTextNumCli;
    private javax.swing.JTextField jtextnumcont;
    // End of variables declaration//GEN-END:variables
}
